### PR TITLE
Fix flaky database acceptance tests.

### PR DESCRIPTION
**Pull request by andrewsomething**

### CODE REVIEW

**Comment by andrewsomething** [comment]
/testacc pkg=digitalocean/database sha=5cd408431e266f669df84f02c9790d0de048a3a1

**Comment by andrewsomething** [comment]
/testacc pkg=digitalocean/database sha=dcb49f8df5a443ebd537d253b5b3f180585df504

**Comment by andrewsomething** [comment]
/testacc pkg=digitalocean/database sha=8793fadc82748e5c9c3a8f0376c0e21d9022abcc

**Comment by andrewsomething** [comment]
/testacc pkg=digitalocean/database sha=c5761cdae1518b36125c05979288e27a0925a6f2

**Comment by andrewsomething** [comment]
/testacc pkg=digitalocean/database sha=60dc9a7fb0658a30320c1082fa262c5ad498081d

**Review by bentranter — APPROVED** [review]

**Pull request merged**
