### PR TITLE
Replace domains string array with object, add image attribute and support job components

### PR DESCRIPTION
**Pull request by acraven**
This is  a spike for #542 and #543 - the image addition works for my use case, but I haven't been able to confirm the domain change yet.

GoLang's not in my skill set, so I'm not aware of any problems my changes may cause. I'm more than happy for others to get involved, so if someone could help out (coding or mentoring) that would be appreciated.

### CODE REVIEW

**Comment by acraven** [comment]
I can confirm that the changes appear to have worked and are visible in the App Spec download.

I do however get the following error thrown as the `terraform apply` completes:
```
Error: [DEBUG] Error setting app spec: &errors.errorString{s:"spec.0.domain.0.wildcard: '' expected type 'bool', got unconvertible type 'string'"}
```

**Comment by acraven** [comment]
The last commit fixes the problem I was seeing after `terraform apply`

**Comment by acraven** [comment]
Also supports changes for #545

**Comment by acraven** [comment]
Job support appears to have worked and is visible in the App Spec download.

**Comment by armanm** [comment]
Would love to see these changes released soon.

Thanks for working on this ❤️

**Comment by andrewsomething** [comment]
Thank you for taking this on @acraven! Sorry for the delayed response over the holidays.

This looks like a great start. I have a bit of high-level feedback:

- It would be great if you could break this up into separate PRs for each feature. It will make it much easier to review and will allow us to merge in parts that are ready to go with out being blocked on ones that might need some more work.
- We should not break existing users with the change to `domains`. We can mark the old `domains` attribute as deprecated to transition users to the new `domain` attribute, but it should continue to function for now. Here's an example from a different resource: https://github.com/digitalocean/terraform-provider-digitalocean/blob/410de8b75b5f214b1a7dfef1fecbfe756f6231df/digitalocean/resource_digitalocean_volume.go#L98-L99
- We should add acceptance tests excising these features. See the existing apps tests for some examples: https://github.com/digitalocean/terraform-provider-digitalocean/blob/master/digitalocean/resource_digitalocean_app_test.go
  - The main Terraform docs should also be useful: https://www.terraform.io/docs/extend/testing/acceptance-tests/index.html
  - The whole test suite takes a _long time_ to run. You can run tests individually using: `make testacc TESTARGS='-run=TestAccDigitalOceanApp_Worker'`

Let me know if there's anything I can do to help.

**Comment by dcoraboeuf** [comment]
Looking forward to have this available soon 👍

**Comment by andrewsomething** [comment]
@acraven Let me know if you need any help on this.

**Comment by andrewsomething** [comment]
@acraven Thank you so much for kicking this off. @rienafairefr has finished up the images work in https://github.com/digitalocean/terraform-provider-digitalocean/pull/565 and jobs in https://github.com/digitalocean/terraform-provider-digitalocean/pull/566

https://github.com/digitalocean/terraform-provider-digitalocean/pull/572 has the domain changes handled in a way that should be non-disruptive for current users.

**Comment by MattIPv4** [comment]
Hey, @acraven - Thanks a ton for this sweet PR! 😄

Would you please shoot me an email when you get a chance?
mcowley at digitalocean dot com 🎉

**Pull request closed without merging**
