### PR TITLE
Fixed issue about database cluster

### PR DESCRIPTION
**Pull request by opeco17**
After calling the following POST endpoint to create database cluster, database cluster should be created and calling GET endpoint should be succeeded
https://github.com/digitalocean/terraform-provider-digitalocean/blob/v2.14.0/digitalocean/resource_digitalocean_database_cluster.go#L248

But, according to #728, 404 error occurs occasionally when calling GET endpoint in the following line
https://github.com/digitalocean/terraform-provider-digitalocean/blob/v2.14.0/digitalocean/resource_digitalocean_database_cluster.go#L483

This PR is the workaround for this issue

### CODE REVIEW

**Comment by danaelhe** [comment]
Thank you so much for the contribution! We will review PR and leave comments as soon as we can.

**Comment by opeco17** [comment]
Sure!
Thank you for reviewing!

**Review by andrewsomething — APPROVED** [review]
:+1:  Looks good.

Sorry for the delay merging over the holidays.

**Comment by MattIPv4** [comment]
Hey, @opeco17 - Thanks a ton for this sweet PR! 😄

Would you please shoot me an email when you get a chance?
mcowley at digitalocean dot com 🎉

**Pull request merged**
