### PR TITLE
Add MONGODB as a database engine option

### PR DESCRIPTION
**Pull request by cnunciato**
This change adds `MONGODB` as an `engine` option to the `databases` block of an App spec. It's necessary for anyone wishing to attach an already-existing managed MongoDB cluster to an App Platform app.

From the [DigitalOcean docs](https://docs.digitalocean.com/products/app-platform/#limits): 

> App Platform’s engine support for dev databases is currently limited to PostgresSQL, but you can create a PostgresSQL, MySQL, Redis, or MongoDB managed database with DigitalOcean for use in your app.

Here's a working plan file that uses this change to provision a managed MongoDB cluster and then an App Platform app with a named reference (`db`) to it:

```tf
terraform {
  required_providers {
    digitalocean = {
      source = "digitalocean/digitalocean"
      version = "~> 2.0"
    }
  }
}

variable "do_token" {
    type = string
}

provider "digitalocean" {
  token = var.do_token
}

resource "digitalocean_database_cluster" "cluster" {
  name       = "some-cluster"
  engine     = "mongodb"
  version    = "4"
  size       = "db-s-1vcpu-1gb"
  region     = "sfo3"
  node_count = 1
}

resource "digitalocean_app" "app" {
  spec {
    name   = "some-app"
    region = "sfo3"

    database {
      cluster_name = digitalocean_database_cluster.cluster.name
      name         = "db"
      engine       = "MONGODB"
      production   = true
    }
  }
}
```

```
$ terraform apply

digitalocean_database_cluster.cluster: Creating...
digitalocean_database_cluster.cluster: Still creating... [10s elapsed]
...
digitalocean_database_cluster.cluster: Creation complete after 6m8s [id=ce4e5dd1-0927-4e55-adab-6b03347ac280]
digitalocean_app.app: Creating...
digitalocean_app.app: Still creating... [10s elapsed]
digitalocean_app.app: Creation complete after 33s [id=df979d07-53cc-4697-a782-e5a79a3a7339]

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.
```

image

### CODE REVIEW

**Review by andrewsomething — APPROVED** [review]
:+1:  Looks great. Thanks @cnunciato!

**Comment by stack72** [comment]
Hey @andrewsomething - any chance of a v2.17.1 for this? ;) We'd love to be able to feature this for a upcoming blog post

**Comment by cnunciato** [comment]
Thank you for the quick response @andrewsomething! 🍻

**Comment by andrewsomething** [comment]
Sure thing @stack72 We got you. https://github.com/digitalocean/terraform-provider-digitalocean/pull/784

**Comment by MattIPv4** [comment]
Hey, @cnunciato - Thanks a ton for this sweet PR! 😄

Would you please shoot me an email when you get a chance?
mcowley at digitalocean dot com 🎉

**Pull request merged**
