### PR TITLE
fix: added missing option to set port on health_check

### LINKED ISSUE #1077: Unable to set port for health_check
# Bug Report

---

## Describe the bug

Unable to set port in health_check block.

### Expected Behavior

Ability to set alternative port for health_check

### Actual Behavior

No option for setting port in health_check block

### Steps to Reproduce

**Terraform Configuration Files**

```terraform
resource "digitalocean_app" "auth-hammerhead" {
  spec {
    name   = "some-app"
    ...
    service {
      http_port          = 4000
      internal_ports     = [1231]
      health_check {
        http_path = "/healthcheck"
      }
      ....
    }
  }
}
```

**Terraform version**

1.6.3
**Debug Output**

**Panic Output**

## Additional context

**Important Factoids**

**References**

### PR DESCRIPTION
**Pull request by nemcikjan**
Fixes #1077

### CODE REVIEW

**Comment by danaelhe** [comment]
🏃 That was quick! Awesome work- could you add a quick test in `digitalocean/app/app_spec.go`?

**Comment by danaelhe** [comment]
And also docs in `digitalocean/docs/resources/app.md` - then it'll be ready to merge

**Comment by nemcikjan** [comment]
@danaelhe added missing test and docs

**Review by danaelhe — APPROVED** [review]
Awesome!! Thank you for the quick fix!

**Comment by danaelhe** [comment]
Will cut a new release now, thanks again.

**Pull request merged**
