### PR TITLE
load-balancers: Add support for size_unit

### PR DESCRIPTION
**Pull request by bbassingthwaite**

### CODE REVIEW

**Review by bentranter — CHANGES_REQUESTED** [review]
Changes look great but could you update the tests as well for the new `size_unit` field? Thanks!

**Comment by bbassingthwaite** [comment]
@bentranter done! Also added a test for using just `size_unit`.

**Review by andrewsomething — CHANGES_REQUESTED** [review]
```
    resource_digitalocean_loadbalancer_test.go:113: Step 2/2 error: Check failed: 1 error occurred:
                * Check 4/13 error: digitalocean_loadbalancer.foobar: Attribute 'size' not found
        
--- FAIL: TestAccDigitalOceanLoadbalancer_Updated (284.68s)
```

Looks like this one needs updating as well:

https://github.com/digitalocean/terraform-provider-digitalocean/blob/130b7a193af7e92d7c8e896888eb280da07c0ca8/digitalocean/resource_digitalocean_loadbalancer_test.go#L166

(GitHub won't let you comment on an unchanged line.)

Also noticing this one failing:

```
    resource_digitalocean_loadbalancer_test.go:471: Step 2/2, expected an error but got none
--- FAIL: TestAccDigitalOceanLoadbalancer_resizeExpectedFailure (104.86s)
```

Does the policy around resizing change with this release?

https://github.com/digitalocean/terraform-provider-digitalocean/blob/130b7a193af7e92d7c8e896888eb280da07c0ca8/digitalocean/resource_digitalocean_loadbalancer_test.go#L444-L448

**Comment by bbassingthwaite** [comment]
> TestAccDigitalOceanLoadbalancer_Updated

Fixed this one up!

> TestAccDigitalOceanLoadbalancer_resizeExpectedFailure

We still have the same policy around resizing, but fixed the issue by moving the param to `size_unit`.

**Review by andrewsomething — APPROVED** [review]
:+1:  Looks good!

**Pull request merged**
