### PR TITLE
WIP AppSpec Alerts

### PR DESCRIPTION
**Pull request by atombrella**
I don't find the documentation for the alerts under https://docs.digitalocean.com/reference/api/api-reference/#operation/create_app
It's quite unfinished, and needs more work before I'll ask for a review or assistance!

### CODE REVIEW

**Comment by atombrella** [comment]
@andrewsomething @danaelhe I'm still interested in getting this finished. I've been somewhat business with other things, but I have a bit of free time to get some progress into this PR. Basically, it's this issue #683 As mentioned, there's not really much documentation in the API pages. But it's supported through the GoLang API, which is what I've primarily used. It's not ideal, though.

**Comment by andrewsomething** [comment]
@atombrella It does look like the docs are lacking a bit for this feature. Let me know if you have any questions.

**Comment by atombrella** [comment]
@andrewsomething Maybe the best help I can get is some input on the approach how it should be coded in Terraform.

```
resource "digitalocean_app" "foobar" {
  spec {
    name = "%s"
    region = "nyc"

    service {
      name               = "go-service"
      environment_slug   = "go"
      instance_count     = 1
      instance_size_slug = "basic-xxs"

      %s

      git {
        repo_clone_url = "https://github.com/digitalocean/sample-golang.git"
        branch         = "main"
      }
    }
  }
  alerts {
    component = [self.resource_name]
    emails    = ["benny@digitalocean.com"]
    slack {
      channel   = "Production Alerts"
      url       = "https://hooks.slack.com/services/T1234567/AAAAAAAA/ZZZZZZ"
    }
    value       = 95
    operator  = "GREATER_THAN"
    window   = "THIRTY_MINUTES"
    type        = "CPU_UTILIZATION"
  }
```

Is taken from one of the tests (pushed and in this PR). Things are not yet running. The component name is always the same as the name of the resource? I think specifying how it should be defined in Terraform is the best help I can get with this stuff. Thank you. 

Poor Benny. I hope nobody has this email alias :smile:

**Comment by andrewsomething** [comment]
@atombrella Sorry for the delayed response. 

There has been some additional information added to the App Spec reference on alerts:

https://docs.digitalocean.com/products/app-platform/references/app-specification-reference/

Alerts are configured as part of the spec. Each component (service, job, or worker) can have  `CPU_UTILIZATION`, `MEM_UTILIZATION`, or `RESTART_COUNT` rules while the top level  app can have  `DEPLOYMENT_FAILED`, `DEPLOYMENT_LIVE`, `DOMAIN_FAILED`, or `DOMAIN_LIVE` rules.

The destination for the alerts defaults to the email of the account. Additionally, to update the destinations with additional emails or Slack webhooks, you need to call a separate endpoint:

https://docs.digitalocean.com/reference/api/api-reference/#operation/assign_alert_destinations

That's a bit awkward for Terraform. I think it might be best to leave that for a future PR. It might require a separate app alert destinations resource. 

So I think the initial interface ends up looking like:

```hcl
resource "digitalocean_app" "foobar" {
  spec {
    name = "foobar"
    region = "nyc"

    alert {
      rule = "DEPLOYMENT_FAILED"
    }

    service {
      name               = "go-service"
      environment_slug   = "go"
      instance_count     = 1
      instance_size_slug = "basic-xxs"

      git {
        repo_clone_url = "https://github.com/digitalocean/sample-golang.git"
        branch         = "main"
      }

      alert {
        value    = 95
        operator = "GREATER_THAN"
        window   = "THIRTY_MINUTES"
        rule     = "CPU_UTILIZATION"
      }

      alert {
        value    = 80
        operator = "GREATER_THAN"
        window   = "THIRTY_MINUTES"
        rule     = "MEM_UTILIZATION"
      }
    }
  }
}
```

**Comment by andrewsomething** [comment]
I'm going to close this out in favor of https://github.com/digitalocean/terraform-provider-digitalocean/pull/797. Thanks for getting this started @atombrella!

**Pull request closed without merging**
