### PR TITLE
Update to Context-aware API v2 functions

### PR DESCRIPTION
**Pull request by atombrella**
All of them found with `staticcheck . | grep SA1019`

This is just a subset of API v2 deprecation updates.

### CODE REVIEW

**Comment by atombrella** [comment]
These are the remaining ones. @andrewsomething @scotchneat

```
❯ staticcheck .  | grep SA1019
config.go:73:29: oauth2.NoContext is deprecated: Use context.Background() or context.TODO() instead.  (SA1019)
}).WaitForState is deprecated: Please use WaitForStateContext to ensure proper plugin shutdown  (SA1019)
provider.go:125:2: p.ConfigureFunc is deprecated: Please use ConfigureContextFunc instead.  (SA1019)
resource_digitalocean_spaces_bucket.go:407:8: lifecycleRule.Prefix is deprecated: Prefix has been deprecated  (SA1019)
resource_digitalocean_spaces_bucket.go:408:24: lifecycleRule.Prefix is deprecated: Prefix has been deprecated  (SA1019)
resource_digitalocean_spaces_bucket.go:780:9: resource.Retry is deprecated: Please use RetryContext to ensure proper plugin shutdown  (SA1019)
```

**Comment by scotchneat** [comment]
@atombrella while reviewing this change, I ran the droplet tests and found an issue during post-test destroy logic that only occurs with the new changes.

I'm working to track down the cause but if you want to reproduce the issue yourself, you can run:

```
go test -timeout 15m -run ^TestAccDigitalOceanDroplet_Basic$ github.com/digitalocean/terraform-provider-digitalocean/digitalocean -v
```

If you set the `TF_LOG=DEBUG` environment variable, you can see the `GET /v2/droplets/<DROPLETID>` being called repeatedly until an error is returned indicating the post-test destroy failed while `waiting for the droplet to be unlocked for destroy`.

The issue stems from [here](https://github.com/digitalocean/terraform-provider-digitalocean/blob/606d32da901bd73698ad3586e7b70e5bcce4fa48/digitalocean/resource_digitalocean_droplet.go#L610) but we're still digging into why.

**Comment by atombrella** [comment]
> @atombrella while reviewing this change, I ran the droplet tests and found an issue during post-test destroy logic that only occurs with the new changes.
> 
> I'm working to track down the cause but if you want to reproduce the issue yourself, you can run:
> 
> ```
> go test -timeout 15m -run ^TestAccDigitalOceanDroplet_Basic$ github.com/digitalocean/terraform-provider-digitalocean/digitalocean -v
> ```
> 
> If you set the `TF_LOG=DEBUG` environment variable, you can see the `GET /v2/droplets/<DROPLETID>` being called repeatedly until an error is returned indicating the post-test destroy failed while `waiting for the droplet to be unlocked for destroy`.
> 
> The issue stems from [here](https://github.com/digitalocean/terraform-provider-digitalocean/blob/606d32da901bd73698ad3586e7b70e5bcce4fa48/digitalocean/resource_digitalocean_droplet.go#L610) but we're still digging into why.

Thanks for the feedback! Perhaps https://github.com/digitalocean/terraform-provider-digitalocean/blob/606d32da901bd73698ad3586e7b70e5bcce4fa48/digitalocean/resource_digitalocean_droplet.go#L687-L700
is one of the culprits (I may be guessing out of the blue).

**Comment by atombrella** [comment]
@scotchneat I reverted a few of the changes in a new commit, and this is the result of the single acceptance test. 

```
--- PASS: TestAccDigitalOceanDroplet_Basic (57.98s)
PASS
ok  	github.com/digitalocean/terraform-provider-digitalocean/digitalocean	57.991s
```

**Review by scotchneat — APPROVED** [review]
Looks good. 
We'll have to investigate the droplet failures further before changing that code to use the context-aware functions.

**Comment by atombrella** [comment]
@scotchneat Yes. I haven't run the entire acceptance test suite, as it unfortunately costs money. `GetOkExists` has a comment that it's not reliable; it was one of the things I reverted in the last commit. Please don't release a new version before there is a proper answer to this.

**Pull request merged**
