### PR TITLE
Allow for Timeouts to be set for Droplet Create Operations

### PR DESCRIPTION
**Pull request by ngharrington**
This is a proposal to solve issue #828  . I do not necessarily think it is an ideal or preferred solution and I am more than open to feedback.

Add Timeout to the resource_digital_ocean_droplet schema for Create, Update, Delete operations. These default to values that keep behavior the same as before if they are not set.  Namely, timeout for all operations is at least 60 minutes. Specifically, by default, timeout for the &resource.StateChangeConf inside waitForDropletAttribute function stays the same by default.

Notably, for deletes and updates, these attribute refreshes happen multiple times per operation, so I decided to just pass through the relevant timeout for every attribute refresh.  Meaning the true timeout for a delete or update would be a multiple of the set timeouts in the schema. 

I additionally updated the droplet tests. The slug used for the image in the current code appears to not exist from my PoV, I changed to an ubuntu distribution but the choice doesn't matter to me one way or the other.

### CODE REVIEW

**Comment by ngharrington** [comment]
@andrewsomething do you or other maintainers have thoughts on this PR, or what I may be able to do to bring it closer to what you folks would want.  (alternatively, if you want to forgo this feature for now due to the way the timeouts behave with respect to state refreshes)

**Comment by danaelhe** [comment]
Thank you so much for your efforts and time on this contribution! I just kicked off the Tests workflow for this PR and will review your changes as soon as we can.

**Comment by ngharrington** [comment]
Thank you so much for the response and for kicking of the tests!

**Review by andrewsomething — APPROVED** [review]
:+1:  Thank you for this improvement. Sorry for taking so long to get it merged. As you say, this might not be the ideal solution, but I do think it is a good step in the right direction and will help unblock people impacted by https://github.com/digitalocean/terraform-provider-digitalocean/issues/828

I did push one additional commit changing Ubuntu 21.10 to 22.04 as it is a long term support release. So we will not need to update it again as soon.

**Pull request merged**
