### PR TITLE
Switch to retryable http client addresses #546

### PR DESCRIPTION
**Pull request by tback**
I replaced the default http client with hashicorps retryable httpclient. That client detects and adapts to http status code 429. 
This is my first PR in this project.

### CODE REVIEW

**Comment by tback** [comment]
Let me know if there is anything I can do to make this any easier on your end.

**Comment by scotchneat** [comment]
@tback thank you for your contribution. I can see where this will be useful in many cases. 
I'm working on understanding the impact to the behavior of the provider and need to determine if there are any cases where we'd want to avoid retries before we accept this change.

**Comment by tback** [comment]
Hi Cesar,

thanks for looking into this. One more thing to add since it might not be
obvious from the PR:
Hashicorp/go-retryablehttp behaves very well in this situation: it
evaluates the retry-after header if available and uses exponential backoff
as fallback (
https://pkg.go.dev/github.com/hashicorp/go-retryablehttp?utm_source=godoc#DefaultBackoff
).

**Comment by scotchneat** [comment]
@tback, I was reading into that backoff behavior and think that's one of the great values this change would offer.

I do have some thoughts. 
1. It would be practical to allow users to override the retryablehttp client's [default values](https://pkg.go.dev/github.com/hashicorp/go-retryablehttp#Client) (like the `RetryWaitMin`, `RetryWaitMax`, and `RetryMax` values) to suite their needs. This would require adding some properties to the [Config](https://github.com/digitalocean/terraform-provider-digitalocean/blob/main/digitalocean/config.go#L21) struct, as well as schema values to the [provider](https://github.com/digitalocean/terraform-provider-digitalocean/blob/main/digitalocean/provider.go#L15) to load from environment variables. 
2. More notable, I'm thinking that a better place to apply this change would be in the [digitalocean/godo](https://github.com/digitalocean/godo) pacakge as that would enable any go client to leverage the retry capabilities.

**Comment by tback** [comment]
@scotchneat thanks for your suggestions. They absolutely make sense to me. I won't have time to implement them over the next months though.
Anybody can take it from here?

**Comment by tback** [comment]
Nevermind.

**Pull request closed without merging**
