### PR TITLE
kubernetes: always perform upgrade check. (#823)

### PR DESCRIPTION
**Pull request by macno**
version check does not depend on node_pool changes

### CODE REVIEW

**Review by scotchneat — CHANGES_REQUESTED** [review]
Just a heads up. Once the conflicts are resolved the `testClusterVersion22` should become `testClusterVersionLatest` due to #826 having been merged.

**Comment by macno** [comment]
@scotchneat I added a function to create the terraform data snippet, so I can reuse the `k8sVersionLatest` variable when checking the version. Hope it's fine for you

**Comment by macno** [comment]
Hi @scotchneat just a check to see if everything is ok on my side or you need me to do something else. Thanks!

**Review by scotchneat — APPROVED** [review]
@macno I apologize for the delay. I had noticed some test failures when running the relevant acceptance tests. However, they're not related to your change. 

This looks good to me. Thanks for addressing this and for the contribution!

**Pull request merged**
